---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"
    - name: Testing role
      ansible.builtin.include_role:
        name: hammadrauf.networkconfig
        tasks_from: main.yml
